using System;
using System.Collections.Generic;

namespace VendasWebAPI.Models
{
    public partial class Permissoes
    {
        public int PermissoesId { get; set; }
        public bool Adicionar { get; set; }
        public bool Guardar { get; set; }
        public bool Atualizar { get; set; }
        public bool Apagar { get; set; }
        public bool Descontos { get; set; }
        public bool Dividas { get; set; }
        public bool Relatorios { get; set; }
        public bool Consultas { get; set; }
        public bool Promocoes { get; set; }
        public bool DataVenda { get; set; }
        public bool Definicoes { get; set; }
        public bool DefinicoesConsultas { get; set; }
        public bool DefinicoesDepartamentos { get; set; }
        public bool Backup { get; set; }
        public bool BackupManual { get; set; }
        public bool BackupAutomatico { get; set; }
        public bool BackupActivarDesativar { get; set; }
        public bool Graficos { get; set; }
        public bool GraficosActivarDesativar { get; set; }
        public bool GraficosLogoMarca { get; set; }
        public bool GruposRestricoes { get; set; }
        public bool Grupos { get; set; }
        public bool GruposAdicionar { get; set; }
        public bool GruposConsultar { get; set; }
        public bool Usuarios { get; set; }
        public bool UsuariosAdicionar { get; set; }
        public bool UsuariosConsultar { get; set; }
        public bool UsuariosOnline { get; set; }
        public bool UsuariosListagem { get; set; }
        public bool UsuariosHistorico { get; set; }
        public bool UsuariosCartao { get; set; }
        public bool UsuariosVendasReport { get; set; }
        public bool Auditoria { get; set; }
        public bool ErrosLogs { get; set; }
        public bool AuditoriaReport { get; set; }
        public bool ErrosLogsReport { get; set; }
        public bool ModuloGeral { get; set; }
        public bool ModuloVendas { get; set; }
        public bool ModuloArmazem { get; set; }
        public bool ModuloRecursosHuamnos { get; set; }
        public bool ModuloContabilidade { get; set; }
        public bool ModuloAdministrativa { get; set; }
        public bool ModuloClinica { get; set; }
        public bool PlanoNecessidadeGeral { get; set; }
        public bool PlanoNecessidade { get; set; }
        public bool PlanoNecessidadeOrdem { get; set; }
        public bool Transferencias { get; set; }
        public bool TransferenciaLotes { get; set; }
        public bool TransferenciaSimples { get; set; }
        public bool ClientesAdicionar { get; set; }
        public bool ClientesConsultar { get; set; }
        public bool ClientesGestaoCartao { get; set; }
        public bool ClientesListagemClientes { get; set; }
        public bool ClientesListagemCartao { get; set; }
        public bool ClientesListagemFaturas { get; set; }
        public bool FornecedorAdicionar { get; set; }
        public bool FornecedorConsultar { get; set; }
        public bool FornecedorListagem { get; set; }
        public bool FornecedorListagemProdutos { get; set; }
        public bool Produtos { get; set; }
        public bool ProdutosAdicionar { get; set; }
        public bool ProdutosEquivalencia { get; set; }
        public bool ProdutosDataValidade { get; set; }
        public bool ProdutosSugestoes { get; set; }
        public bool ProdutosListagem { get; set; }
        public bool ProdutosListagemSugestoes { get; set; }
        public bool Stock { get; set; }
        public bool StockAdicionar { get; set; }
        public bool StockCalcPrecos { get; set; }
        public bool StockListagem { get; set; }
        public bool ProdutsStocksAll { get; set; }
        public bool FpagamentosAdicionar { get; set; }
        public bool FpagamentosConsultas { get; set; }
        public bool FaturarGeral { get; set; }
        public bool VendasAdicionar { get; set; }
        public bool VendasAdicionarArmazem { get; set; }
        public bool VendasProforma { get; set; }
        public bool VendasEncomendas { get; set; }
        public bool VendasConsultasGerais { get; set; }
        public bool VendasListagens { get; set; }
        public bool VendasReport { get; set; }
        public bool BtnRelatorioGeral { get; set; }
        public bool FaturasListagens { get; set; }
        public bool FaturasSimplificadas { get; set; }
        public bool FaturasDetalhes { get; set; }
        public bool Caixa { get; set; }
        public bool CaixaDiario { get; set; }
        public bool CaixaDesconto { get; set; }
        public bool CaixaAnual { get; set; }
        public bool CaixaRemocao { get; set; }
        public bool InventarioSimples { get; set; }
        public bool InventarioAvancado { get; set; }
        public bool InventarioContabilistico { get; set; }
        public bool DivisaoEmpresa { get; set; }
        public bool Departamento { get; set; }
        public bool DepartamentoAdicionar { get; set; }
        public bool DepartamentoConfig { get; set; }
        public bool Organizacoes { get; set; }
        public bool Categorias { get; set; }
        public bool SubCategorias { get; set; }
        public bool Provincias { get; set; }
        public bool Monicipios { get; set; }
        public bool StockArmazem { get; set; }
        public bool StockArmazemConsutas { get; set; }
        public bool StockPontos { get; set; }
        public bool TransferenciaReport { get; set; }
        public bool ArmazemReport { get; set; }
        public bool EstadoMercadoria { get; set; }
        public bool BtnInventariosFechosArmazem { get; set; }
        public int GrupoId { get; set; }
        public bool StockHistorico { get; set; }
        public bool FpagamentosConsultasReport { get; set; }
        public bool StocksGestaoImagem { get; set; }
        public bool AbrirInventarios { get; set; }
        public bool ImagensGestaoF { get; set; }
        public bool EmailSender { get; set; }
        public bool EnvioRecepcaoEmail { get; set; }
        public bool CadBarra { get; set; }
        public bool WizardSistema { get; set; }
        public bool MigracaoDados { get; set; }
        public bool BackupHelps { get; set; }
        public bool AnalisedeDados { get; set; }
        public bool Conection { get; set; }
        public bool CaixaConsultasGeral { get; set; }
        public bool VendasReservas { get; set; }
        public bool IsCaixaOnly { get; set; }
        public bool GestaoDadosApagar { get; set; }
        public bool FaturasAntigas { get; set; }
        public bool FaturasEstatisticas { get; set; }
        public bool Pedidos { get; set; }
        public bool DashBoard { get; set; }

        public virtual Grupos Grupo { get; set; }
    }
}
